# Generated by Django 5.2.12 on 2026-03-21 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_rename_uploaded_at_prescription_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dose_flag',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dose_flag_reason',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='duration',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='instructions',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('processed_empty', 'Processed Empty'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
